### ISSUE TITLE
AndroidX Support.

### ISSUE THREAD

**Issue by HPH92** [blackmenthor/flutter-introduction-tooltip#2]
Hey! Thanks for taking your time and creating this package. 

When I added this to the project, it will not build, and here is the reason:

WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX. See https://goo.gl/CP92wY for more information on the problem and how to fix it. This warning prints for all Android build failures. The real root cause of the error may be unrelated.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'flutter_introduction_tooltip' is using version 1.2.30.

Just so you know it! 

Kind Regards.
Henrik Hansen.

Edit:

Tried to make a local copy and change the Kotlin build.
But now it will not run because of: 

I/flutter (10458): ERROR 'package:flutter/src/rendering/box.dart': Failed assertion: line 1482 pos 12: 'hasSize': RenderBox was not laid out: RenderFractionalTranslation#e10de NEEDS-LAYOUT NEEDS-PAINT

catch in line 548 in flutter_introduction_tooltip.dart 

So I can't test it :(  Because nothing is happening.

**Comment by blackmenthor** [comment]
Hi, sure i'll fix this problem now.

We're gonna have to migrate to AndroidX anyway later on. i'll create a PR for this bug.

Thanks for creating the issue

**Comment by blackmenthor** [comment]
PR merged on 

[https://github.com/blackmenthor/flutter-introduction-tooltip/pull/3](url)
