### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by willladislaw** [blackmenthor/flutter-introduction-tooltip#6]
pub get failed (1; Because my_app depends on flutter_introduction_tooltip ^0.1.0 which doesn't match any versions, version solving failed.)

**Comment by blackmenthor** [comment]
Hi! Thanks for creating an issue, but I believe you've been using an nonexistent version.

You should change it to other version available, you can see it here on the pub page (https://pub.dev/packages/flutter_introduction_tooltip)

Closing this
